<?php

namespace app\models;

class User extends Model
{
    public $name = 'usuarios';
    public $fillable = [];

    public function __construct($nome)
    {
        parent::__construct($nome);
    }

    public function create($dados)
    {
        parent::create($dados); // TODO: Change the autogenerated stub
    }
}